### ISSUE TITLE
Add the support for continuous integration

### ISSUE THREAD

**Issue by rouvoy** [gisselFdez/PFE-M2IAGL#8]
You can add a continuous integration support for your project using [TravisCI](https://travis-ci.org) and include the associated [status badge](https://docs.travis-ci.com/user/status-images/) from the home page.

**Comment by rouvoy** [comment]
Please don't forget to include a Travis badge from the main Readme.md file as a link to the Travis instance.

**Comment by gisselFdez** [comment]
I had forgotten but I just add it. Thank you!
